# Generated by Django 3.2.4 on 2021-06-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210622_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomprivate',
            old_name='secounf_user',
            new_name='secound_user',
        ),
    ]
