# Generated by Django 3.2.4 on 2021-06-23 04:25

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_secounf_user_chatroomprivate_secound_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=chat.models.get_default_picture, upload_to=chat.models.get_picture),
        ),
    ]
